* About the template
** Why this template?
- Remove friction of setup of new project
- Remove friction of writing the initial tests
** Project layout
- This follows src layout w poetrty (~--src~) as it integrates better w pytest atm
- Have all files that you intend to ~execute~ in the top-level directory
- Only import things that are at the same level or nested folders
*** src vs flat layout
- See [[https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/][src layout vs flat layout]]
- src layout
  - Putting your package inside a src directory means that you have to install it the way your users will
  - Python implicitly adds the current directory to ~sys.path~
- Flat layout
  - This is good if the python project just has one package. This is normally the case. One repo = one python package. The name of the repo in pyproject is the same as the directory name in top level.

* Style and other suggestions on python
** Workflow
- Running tests in watch mode w entr and ~pytest~
- Debugging w pudb + ipython + snoop
- Do not have a module name right inside the package that matches a package name
- Always launch from an script outside the package
** Installation & venv
- [[https://chriswarrick.com/blog/2023/01/15/how-to-improve-python-packaging/][How to improve Python packaging, or why fourteen tools are at least twelve too many | Chris Warrick]]
- venvs are folders with symlinks to a system-installed Python, and their own set of site-packages.
- ~editable mode~ is useful when building local packages and using them elsewhere in some other package, lets you reuse stuff without reinstalling the package. Otherwise once you make a change, you need to reinstall the package so that the copy that the importing package is using is updated. poetry installs in editable mode by default for your developing repo.
** Publishing
- ~poetry.lock~ makes no difference if you're publishing your project as a library for others to use.
** Testing
- Test files can just be there in the ~tests/~ directory. no further categorization needed. Files that contain tests just need to start with ~test_~
